import './globals.css';
import Footer from './ui/footer';
import { Navbar } from './ui/navbar';

import type { Metadata } from 'next';
import type { JSX } from 'react';

import type { NavbarProps } from './ui/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navItems: NavbarProps = {
  logo: {
    url: 'https://www.shadcnblocks.com',
    src: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/logos/shadcnblockscom-icon.svg',
    alt: 'logo',
    title: 'Shadcnblocks.com',
  },
  menu: [{ title: 'Home', url: '/' }],
  auth: {
    signin: { title: 'Sign in', url: '/sign-in' },
    signup: { title: 'Sign up', url: '/sign-up' },
  },
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>): JSX.Element => (
  <html lang="en">
    <body className="font-sans antialiased">
      <Navbar auth={navItems.auth} logo={navItems.logo} menu={navItems.menu} />
      <div>{children}</div>
      <Footer auth={navItems.auth} logo={navItems.logo} menu={navItems.menu} />
    </body>
  </html>
);

export default RootLayout;
