import ThemeProvider from '@/components/theme';

import './globals.css';

import Footer from '@/app/ui/footer';
import { Navbar } from '@/app/ui/navbar';

import { Toaster } from '@/components/ui/sonner';

import type { Metadata } from 'next';
import type { JSX } from 'react';

import type { NavbarProps } from './ui/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navItems: NavbarProps = {
  logo: {
    url: '/',
    src: 'https://upload.wikimedia.org/wikipedia/en/4/49/WPI_Engineers_primary_logo.svg',
    alt: 'logo',
    title: 'GoatRide',
  },
  menu: [
    { title: 'Home', url: '/' },
    { title: 'Posts', url: '/posts' },
    { title: 'Settings', url: '/settings' },
  ],
  auth: {
    signin: { title: 'Sign in', url: '/sign-in' },
    signup: { title: 'Sign up', url: '/sign-up' },
  },
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>): JSX.Element => (
  <html suppressHydrationWarning lang="en">
    <body className="font-sans antialiased">
      <ThemeProvider disableTransitionOnChange enableSystem attribute="class" defaultTheme="system">
        <Toaster closeButton position="top-center" />
        <Navbar auth={navItems.auth} logo={navItems.logo} menu={navItems.menu} />
        <div>{children}</div>
        <Footer auth={navItems.auth} logo={navItems.logo} menu={navItems.menu} />
      </ThemeProvider>
    </body>
  </html>
);

export default RootLayout;
